module.exports = {
    NODE_PROFESSION: 'Profession',
    NODE_INSTITUTE: 'Institute',
    NODE_PERSON: 'Person',
    NODE_JOBROLE: 'Role',
    NODE_LOCATION: 'Location',
    NODE_QUALIFICATION: 'Qualification',
    NODE_LANGUAGE: 'Language',
    NODE_SKILL: 'Skill',
    NODE_CENTRE: 'Centre',
    NODE_PROPERTY_NAME: 'name',
    NODE_WORKPLACE: 'WorkPlace',
    NODE_DESG: 'Designation',
    REL_QUALIFIED_AS: 'Qualified_As',
    REL_QUALIFIED_IN: 'Qualified_In',
    REL_MAJOR_SUBJECT_AS: 'Major_Subject_As',
    REL_OFFERS: 'Offers',
    REL_QUALIFIED_FROM: 'Qualified_From',
    REL_WORKED_WITH: 'Worked_With',
    REL_WORKED_IN: 'Worked_In',
    REL_WORKED_AS: 'Worked_As',
    REL_WORKED_ON: 'Worked_On',
    REL_LIVES_IN: 'Lives_In',
    REL_SPEAK: 'Speak',
    REL_WRITE: 'Write',
    REL_READ: 'Read',
    REL_NATIV_LANG: 'Nativ_Lang',
    REL_PREF_LANG: 'Pref_Lang',
    REL_KNOWS: 'Knows',
    REL_PROPERTY_YEARS: 'Years',
    REL_JOB_ROLE: 'Expected_JobRole',
    REL_SKILL: 'Preffered_JobRole_Skill',
    REL_PREFFERED_LOCATION: 'Prefferd_Job_Location',
    REL_JOB_LOOKING: 'Looking_For_Job',
    PROP_JOB_LOOKING: 'lookingForJob',
    PROP_ROLE:'Role',
    PROP_LOCATION:'Location',
    PROP_DURATION:'Duration'
};